# Generated by Django 6.0.6 on 2026-07-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_note_coursr_note_course_note_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
    ]
